object Versions {
    const val appCompat = "1.4.0"
    const val gradle = "7.2.0"
    const val kotlin = "1.6.10"
    const val androidx_compose = "1.1.1"
    const val compose_nav = "2.5.2"
    const val compose_lifecycle = "2.5.1"
    const val compose_animations = "0.21.3-beta"
    const val coil = "1.4.0"
    const val material = "1.4.0"
    const val constraintLayout = "2.1.1"
    const val androidx_viewmodel = "2.3.1"
    const val coroutines = "1.6.1"
    const val androidx_fragment = "1.3.6"
    const val compose_theme_adapter = "1.1.2"
    const val androidx_lifecycle = "2.4.0"
    const val androidx_navigation = "2.3.5"
    const val hilt = "1.0.0"
    const val hilt_plugin = "2.40.1"
    const val hilt_compiler = "2.38.1"
    const val serialization_version = "1.3.0"
    const val ktor = "2.0.3"
    const val androidx_test = "1.3.0"
    const val mockk = "1.12.2"
    const val turbine = "0.6.1"
}
